### ISSUE TITLE
Updated for MP Implementation of OAuth2?

### ISSUE THREAD

**Issue by fbgluck** [faithchapel/mp-rest-documentation#2]
Has this documentation been updated for Ministry Platform's recent update to use OAuth2?

Thanks

**Comment by ChrisMonson** [comment]
Hello! So the information in this document is a bit higher level than that so as far as I know there isn't really anything the is impacted by the OAuth updates. There was some outdated information about where the api client credentials should be stored and I went ahead and updated that.
