### ISSUE TITLE
Nested "Form_Response" and "Form_Response_Answers" - Is it possible in one POST/PUT request?

### ISSUE THREAD

**Issue by Cdrew92** [faithchapel/mp-rest-documentation#4]
#### PROBLEM: ####
I would like to PUT/POST a request that creates a "Form_Response" record, along with the associated "Form_Response_Answers"

#### EXAMPLE: ####
- The request below creates (1) "Form_Response" record, and (1) associated "Form_Response_Answers" record containing "First_Name"

```
Table: Form_Response_Answers
Method: PUT
AllowCreate: true

[
  {
    "Form_Field_ID": 3238,
    "Response": "<FIRST NAME GOES HERE> (JOHN)",
    "Form_Response_ID": {
          "Form_Response_ID": null,
          "Response_Date": "11/22/2022 3:00 PM",
          "Contact_ID":123543,
          "First_Name": "john",
          "Last_Name": "doe",
          "Email_Address": "john.doe@test.com",
          "Phone_Number": "123-456-7891",
          "Congregation_ID": 1,
          "Form_ID": {
               "Form_ID": 518,
               "Form_Title": "WEBSITE - Plan Your Visit (I'm Coming This Sunday)",
               "Get_Contact_Info": false,
               "Get_Address_Info": false,
        }         
     }
  }
]
```

#### QUESTION: ####
Is it possible to extend/modify this request body to submit multiple "Form_Response_Answers" in (1) PUT/POST request, while at the same time creating a new "Form_Response" record?

#### WHAT I'VE TRIED ####
Alternatively, I could make a bare request to the "Form_Response" table, save the resulting "Form_Response_ID" and then make (1) PUT request to "Form_Response"Answers", but it's certainly not ideal.

Any help is appreciated!

**Comment by matthewnitschke** [comment]
Hey @Cdrew92!

This repo is an unofficial documentation of the rest api that ministry platform provides, and not supported by the official ministry platform development team.

Also, the previous maintainers of this repo (myself and @ChrisMonson) no longer work on any ministry platform related applications.

Unless @ChrisMonson has an idea, I’d suggest reaching out to your contact at ministry platform, and they should be able to get you the information you are looking for

Feel free to post a PR based on what you learn! We are happy to continue to add to what this repo already holds
